# TOML Document

title = "TOML Document"

[Validator]
operatorAddr = "terravaloper~"

[Feeder]
password = ""

[APIs]
	[APIs.LUNA.KRW]
	coinone = "https://tb.coinone.co.kr/api/v1/tradehistory/recent/?market=krw&target=luna"

	# API key is required
	# https://currencylayer.com/product
	[APIs.STABLES]
	currencylayer = "https://api.currencylayer.com/live?access_key="

	[APIs.sdr]
	imf = "https://www.imf.org/external/np/fin/data/rms_five.aspx?tsvflag=Y"

	[APIs.band]
	band = "https://poa-api.bandchain.org"

[Options]
interval = 200
